In [1]:
! pip install faker pandas

Requirement already satisfied: faker in c:\programdata\anaconda3\lib\site-packages (40.36.0)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: tzdata in c:\programdata\anaconda3\lib\site-packages (from faker) (2025.2)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
from faker import Faker 
import pandas as pd
import random
fake=Faker()
Faker.seed(42)
random.seed(42)
NUM_RECORDS=50000
product_catalog = [
    "CardioSafe 10mg", "CardioSafe 20mg", "GlucoBalance", "PainRelief Plus",
    "ImmunoBoost", "RespiClear", "NeuroCalm", "DermaHeal", "OrthoFlex", "ThyroCare"
]
sales_records=[]
for transaction_id in range(1,NUM_RECORDS+1):
    product_name=random.choice(product_catalog)
    quantity_sold=random.randint(1,500)
    unit_price=round(random.uniform(50,2000),2)
    total_revenue=round(quantity_sold*unit_price,2)
    transaction_date=fake.date_between(start_date='-2y',end_date='today')
    sales_records.append({
        "transaction_id": transaction_id,
        "transaction_date": transaction_date,
        "product_name": product_name,
        "quantity_sold": quantity_sold,
        "unit_price": unit_price,
        "total_revenue": total_revenue
    })
sales_df = pd.DataFrame(sales_records)
sales_df.head(10)

,transaction_id,transaction_date,product_name,quantity_sold,unit_price,total_revenue
0,1,2026-01-26,CardioSafe 20mg,13,1496.02,19448.26
1,2,2024-12-12,PainRelief Plus,115,322.10,37041.50
2,3,2024-10-06,CardioSafe 20mg,347,1494.30,518522.10
3,4,2026-04-15,OrthoFlex,45,1201.46,54065.70
4,5,2025-04-18,CardioSafe 10mg,16,232.71,3723.36
5,6,2025-03-26,PainRelief Plus,259,1223.94,317000.46
6,7,2025-03-09,OrthoFlex,102,1446.24,147516.48
7,8,2025-01-03,OrthoFlex,215,479.86,103169.90
8,9,2026-04-12,ThyroCare,143,1628.39,232859.77
9,10,2024-12-05,CardioSafe 10mg,389,1621.35,630705.15

In [3]:
NUM_MRS=50
territory_list = [
    "North Zone", "South Zone", "East Zone", "West Zone",
    "Central Zone", "North-East Zone"
]
mr_records=[]
for mr_id in range(1,NUM_MRS+1):
    mr_name=fake.name()
    assigned_territory=random.choice(territory_list)
    hire_date=fake.date_between(start_date='-8y',end_date='-6M')
    mr_records.append({
        "mr_id": mr_id,
        "mr_name": mr_name,
        "territory": assigned_territory,
        "hire_date": hire_date
    })
mr_df=pd.DataFrame(mr_records)
print(mr_df.head(10))
sales_df["mr_id"]=[random.randint(1,NUM_MRS) for _ in range (len(sales_df))]
sales_df.head(10)

   mr_id            mr_name        territory   hire_date
0      1  Christian Johnson     Central Zone  2022-03-22
1      2     Crystal Larson     Central Zone  2019-06-07
2      3        Debra Greer  North-East Zone  2019-03-19
3      4   Meghan Hernandez       North Zone  2020-10-08
4      5    Michael Goodwin        East Zone  2020-04-12
5      6    Jennifer Pruitt        West Zone  2020-11-29
6      7    Sean Fisher DVM        East Zone  2018-10-27
7      8       Madison Boyd        East Zone  2019-10-14
8      9   Rebecca Robinson        East Zone  2021-07-09
9     10    Victoria Nelson       South Zone  2025-07-12

,transaction_id,transaction_date,product_name,quantity_sold,unit_price,total_revenue,mr_id
0,1,2026-01-26,CardioSafe 20mg,13,1496.02,19448.26,40
1,2,2024-12-12,PainRelief Plus,115,322.10,37041.50,25
2,3,2024-10-06,CardioSafe 20mg,347,1494.30,518522.10,20
3,4,2026-04-15,OrthoFlex,45,1201.46,54065.70,37
4,5,2025-04-18,CardioSafe 10mg,16,232.71,3723.36,40
5,6,2025-03-26,PainRelief Plus,259,1223.94,317000.46,24
6,7,2025-03-09,OrthoFlex,102,1446.24,147516.48,41
7,8,2025-01-03,OrthoFlex,215,479.86,103169.90,48
8,9,2026-04-12,ThyroCare,143,1628.39,232859.77,3
9,10,2024-12-05,CardioSafe 10mg,389,1621.35,630705.15,24

In [4]:
NUM_DOCTORS=200
specializations = [
    "Cardiologist", "Endocrinologist", "General Physician",
    "Pulmonologist", "Neurologist", "Dermatologist", "Orthopedic"
]
specialization_weights = [25, 15, 25, 10, 10, 5, 10]
hospital_list = [
    "Apollo Care Hospital", "Fortis Wellness Center", "City General Hospital",
    "Sunrise Multispeciality", "Lakeview Medical Center", "Metro Health Institute"
]
doctor_records=[]
for doctor_id in range(1,NUM_DOCTORS+1):
    doctor_name = "Dr. " + fake.name()
    assigned_specialization=random.choices(specializations,weights=specialization_weights,k=1)[0]
    affiliated_hospital = random.choice(hospital_list)
    doctor_records.append({
        "doctor_id": doctor_id,
        "doctor_name": doctor_name,
        "specialization": assigned_specialization,
        "affiliated_hospital": affiliated_hospital
    })
doctors_df = pd.DataFrame(doctor_records)
print(doctors_df.head(10))
sales_df["doctor_id"] = [random.randint(1, NUM_DOCTORS) for _ in range(len(sales_df))]
sales_df.head(10)

   doctor_id           doctor_name     specialization      affiliated_hospital
0          1    Dr. Valerie Jensen       Cardiologist  Sunrise Multispeciality
1          2       Dr. Ashley Holt       Cardiologist     Apollo Care Hospital
2          3    Dr. Emily Crawford      Dermatologist    City General Hospital
3          4  Dr. Timothy Reynolds  General Physician  Lakeview Medical Center
4          5       Dr. Tyler Welch  General Physician  Sunrise Multispeciality
5          6    Dr. Donald Sanchez         Orthopedic   Metro Health Institute
6          7     Dr. Jessica Mcgee  General Physician   Metro Health Institute
7          8     Dr. Samuel Powers       Cardiologist    City General Hospital
8          9         Dr. Mary Snow       Cardiologist     Apollo Care Hospital
9         10  Dr. Cynthia Anderson       Cardiologist  Sunrise Multispeciality

,transaction_id,transaction_date,product_name,quantity_sold,unit_price,total_revenue,mr_id,doctor_id
0,1,2026-01-26,CardioSafe 20mg,13,1496.02,19448.26,40,65
1,2,2024-12-12,PainRelief Plus,115,322.10,37041.50,25,185
2,3,2024-10-06,CardioSafe 20mg,347,1494.30,518522.10,20,19
3,4,2026-04-15,OrthoFlex,45,1201.46,54065.70,37,9
4,5,2025-04-18,CardioSafe 10mg,16,232.71,3723.36,40,69
5,6,2025-03-26,PainRelief Plus,259,1223.94,317000.46,24,156
6,7,2025-03-09,OrthoFlex,102,1446.24,147516.48,41,38
7,8,2025-01-03,OrthoFlex,215,479.86,103169.90,48,190
8,9,2026-04-12,ThyroCare,143,1628.39,232859.77,3,155
9,10,2024-12-05,CardioSafe 10mg,389,1621.35,630705.15,24,195

In [5]:
messy_sales_df=sales_df.copy()
num_missing_price=int(.02*len(messy_sales_df))
missing_price_indices=random.sample(range(len(messy_sales_df)),num_missing_price)
messy_sales_df.loc[missing_price_indices,"unit_price"]=None
num_missing_qty=int(0.015*len(messy_sales_df))
missing_qty_indices = random.sample(range(len(messy_sales_df)), num_missing_qty)
messy_sales_df.loc[missing_qty_indices, "quantity_sold"] = None
duplicate_indices = random.sample(range(len(messy_sales_df)), 300)
duplicate_rows = messy_sales_df.iloc[duplicate_indices]
messy_sales_df = pd.concat([messy_sales_df, duplicate_rows], ignore_index=True)
num_messy_case = int(0.05 * len(messy_sales_df))
messy_case_indices = random.sample(range(len(messy_sales_df)), num_messy_case)
for idx in messy_case_indices:
    if random.choice([True,False]):
        messy_sales_df.loc[idx, "product_name"] = messy_sales_df.loc[idx, "product_name"].lower()
    else:
        messy_sales_df.loc[idx, "product_name"] = messy_sales_df.loc[idx, "product_name"].upper()
print("Missing values per column:")
print(messy_sales_df.isnull().sum())
print("\nTotal rows now:", len(messy_sales_df))
print("\nSample of inconsistent product names:")
print(messy_sales_df.loc[messy_case_indices, "product_name"].head(5))

Missing values per column:
transaction_id         0
transaction_date       0
product_name           0
quantity_sold        757
unit_price          1003
total_revenue          0
mr_id                  0
doctor_id              0
dtype: int64

Total rows now: 50300

Sample of inconsistent product names:
32580          orthoflex
18284    PAINRELIEF PLUS
38620          dermaheal
39031          NEUROCALM
2661        glucobalance
Name: product_name, dtype: object

In [6]:
import sqlite3

In [7]:
conn=sqlite3.connect("pharma_sales.db")
messy_sales_df.to_sql("sales",conn,if_exists="replace",index=False)
mr_df.to_sql("medical_representatives",conn,if_exists="replace",index=False)
doctors_df.to_sql("doctors",conn,if_exists="replace",index=False)
print("All three tables written successfully to pharma_sales.db")
test_query = """
SELECT product_name, COUNT(*) AS times_sold, SUM(total_revenue) AS total_revenue_generated
FROM sales
group by product_name
order by total_revenue_generated DESC
"""
result_df=pd.read_sql(test_query,conn)
print(result_df)

All three tables written successfully to pharma_sales.db
       product_name  times_sold  total_revenue_generated
0         DermaHeal        4875             1.253942e+09
1         OrthoFlex        4862             1.252692e+09
2   CardioSafe 20mg        4803             1.250304e+09
3         ThyroCare        4775             1.243151e+09
4         NeuroCalm        4824             1.233253e+09
5        RespiClear        4724             1.230723e+09
6       ImmunoBoost        4746             1.218268e+09
7      GlucoBalance        4772             1.218171e+09
8   PainRelief Plus        4735             1.202788e+09
9   CardioSafe 10mg        4669             1.171078e+09
10        THYROCARE         148             4.024751e+07
11        neurocalm         146             3.975814e+07
12        dermaheal         140             3.851123e+07
13     GLUCOBALANCE         150             3.623323e+07
14        ORTHOFLEX         138             3.616757e+07
15     glucobalance         127             3.434132e+07
16      immunoboost         128             3.219995e+07
17  PAINRELIEF PLUS         111             3.141726e+07
18        thyrocare         133             3.074758e+07
19  cardiosafe 20mg         122             3.074306e+07
20      IMMUNOBOOST         122             3.036202e+07
21  CARDIOSAFE 10MG         111             3.035029e+07
22  CARDIOSAFE 20MG         122             2.999743e+07
23  painrelief plus         123             2.941836e+07
24        orthoflex         114             2.927529e+07
25       RESPICLEAR         118             2.873336e+07
26  cardiosafe 10mg         110             2.733010e+07
27        NEUROCALM         128             2.712932e+07
28       respiclear         108             2.578353e+07
29        DERMAHEAL         116             2.564921e+07

In [8]:
join_query="""
select
s.transaction_id,
s.transaction_date,
s.product_name,
s.quantity_sold,
s.unit_price,
s.total_revenue,
m.mr_name,
m.territory,
d.doctor_name,
d.specialization
from sales as s
JOIN medical_representatives AS m ON s.mr_id = m.mr_id
JOIN doctors AS d ON s.doctor_id = d.doctor_id
LIMIT 10
"""
joined_df=pd.read_sql(join_query,conn)
print(joined_df)

   transaction_id transaction_date     product_name  quantity_sold  \
0               1       2026-01-26  CardioSafe 20mg           13.0
1               2       2024-12-12  PainRelief Plus          115.0
2               3       2024-10-06  CardioSafe 20mg          347.0
3               4       2026-04-15        OrthoFlex           45.0
4               5       2025-04-18  CardioSafe 10mg           16.0
5               6       2025-03-26  PainRelief Plus          259.0
6               7       2025-03-09        OrthoFlex          102.0
7               8       2025-01-03        OrthoFlex          215.0
8               9       2026-04-12        ThyroCare          143.0
9              10       2024-12-05  CardioSafe 10mg          389.0

   unit_price  total_revenue            mr_name        territory  \
0     1496.02       19448.26       Carlos Davis     Central Zone
1      322.10       37041.50     Nicole Navarro       South Zone
2     1494.30      518522.10   Jennifer Hancock        East Zone
3     1201.46       54065.70       Kelly Brooks       North Zone
4      232.71        3723.36       Carlos Davis     Central Zone
5     1223.94      317000.46      James Vasquez        East Zone
6     1446.24      147516.48  Mr. Travis Nguyen        East Zone
7      479.86      103169.90        Sarah Short       North Zone
8     1628.39      232859.77        Debra Greer  North-East Zone
9     1621.35      630705.15      James Vasquez        East Zone

          doctor_name     specialization
0     Dr. Brent Lewis        Neurologist
1  Dr. Brian Phillips  General Physician
2    Dr. Paul Oconnor  General Physician
3       Dr. Mary Snow       Cardiologist
4      Dr. Eric Giles    Endocrinologist
5     Dr. Darren Hall      Pulmonologist
6    Dr. Stephen Wolf       Cardiologist
7    Dr. Troy Aguilar      Pulmonologist
8  Dr. Felicia Vargas  General Physician
9      Dr. Mary Brady        Neurologist

In [9]:
mr_revenue_query = """
SELECT 
    m.mr_id,
    m.mr_name,
    m.territory,
    COUNT(*) AS total_transactions,
    SUM(s.total_revenue) AS total_revenue_generated,
    ROUND(AVG(s.total_revenue), 2) AS avg_revenue_per_sale
FROM sales AS s
JOIN medical_representatives AS m ON s.mr_id = m.mr_id
GROUP BY m.mr_id, m.mr_name, m.territory
ORDER BY total_revenue_generated DESC
"""
mr_revenue_df = pd.read_sql(mr_revenue_query, conn)
print(mr_revenue_df.head(10))
print("\nTotal MRs in result:", len(mr_revenue_df))

   mr_id            mr_name        territory  total_transactions  \
0      7    Sean Fisher DVM        East Zone                1046
1     50     Monica Collins       North Zone                1035
2     11   Christopher Ryan       North Zone                1005
3     49        Haley Smith        East Zone                1020
4     31    Courtney Bryant       South Zone                1034
5     35      David Collins       North Zone                1051
6     34     Steven Shelton       North Zone                1012
7     12      Tonya Holland       South Zone                1053
8     45        Marc Watson  North-East Zone                1047
9     41  Mr. Travis Nguyen        East Zone                1026

   total_revenue_generated  avg_revenue_per_sale
0             2.749138e+08             262823.94
1             2.739670e+08             264702.44
2             2.728051e+08             271447.91
3             2.723102e+08             266970.83
4             2.717645e+08             262828.34
5             2.703787e+08             257258.49
6             2.702442e+08             267039.72
7             2.697112e+08             256135.97
8             2.687437e+08             256679.73
9             2.680003e+08             261208.90

Total MRs in result: 50

In [10]:
territory_rank_query = """
SELECT 
    m.mr_id,
    m.mr_name,
    m.territory,
    SUM(s.total_revenue) AS total_revenue_generated,
    RANK() OVER (
        PARTITION BY m.territory 
        ORDER BY SUM(s.total_revenue) DESC
    ) AS rank_within_territory
FROM sales AS s
JOIN medical_representatives AS m ON s.mr_id = m.mr_id
GROUP BY m.mr_id, m.mr_name, m.territory
ORDER BY m.territory, rank_within_territory
"""
territory_rank_df = pd.read_sql(territory_rank_query, conn)
print(territory_rank_df)

    mr_id              mr_name        territory  total_revenue_generated  \
0       1    Christian Johnson     Central Zone             2.645044e+08
1      46          Bonnie Hall     Central Zone             2.629221e+08
2      13         Melinda Buck     Central Zone             2.596650e+08
3      40         Carlos Davis     Central Zone             2.583330e+08
4      42  Dr. Tyler Adams DVM     Central Zone             2.580167e+08
5      23    Michelle Mitchell     Central Zone             2.570706e+08
6      21       Charles Gordon     Central Zone             2.542162e+08
7       2       Crystal Larson     Central Zone             2.466356e+08
8       7      Sean Fisher DVM        East Zone             2.749138e+08
9      49          Haley Smith        East Zone             2.723102e+08
10     41    Mr. Travis Nguyen        East Zone             2.680003e+08
11     39          Thomas Ross        East Zone             2.674126e+08
12      8         Madison Boyd        East Zone             2.669750e+08
13     30     Melissa Thompson        East Zone             2.659931e+08
14      9     Rebecca Robinson        East Zone             2.646357e+08
15     16        Thomas Harmon        East Zone             2.640928e+08
16     24        James Vasquez        East Zone             2.589368e+08
17     20     Jennifer Hancock        East Zone             2.524073e+08
18     27      Craig Blanchard        East Zone             2.431703e+08
19     19         Wesley Brown        East Zone             2.407533e+08
20      5      Michael Goodwin        East Zone             2.405477e+08
21     50       Monica Collins       North Zone             2.739670e+08
22     11     Christopher Ryan       North Zone             2.728051e+08
23     35        David Collins       North Zone             2.703787e+08
24     34       Steven Shelton       North Zone             2.702442e+08
25     14       Rebecca Miller       North Zone             2.645639e+08
26      4     Meghan Hernandez       North Zone             2.609886e+08
27     37         Kelly Brooks       North Zone             2.497409e+08
28     33         Timothy Hall       North Zone             2.495697e+08
29     48          Sarah Short       North Zone             2.476448e+08
30     15          Kurt Clarke       North Zone             2.425233e+08
31     17       Cynthia Nguyen       North Zone             2.375289e+08
32     45          Marc Watson  North-East Zone             2.687437e+08
33     43    Christian Holland  North-East Zone             2.673356e+08
34      3          Debra Greer  North-East Zone             2.518998e+08
35     26        Roberta Adams  North-East Zone             2.494651e+08
36     31      Courtney Bryant       South Zone             2.717645e+08
37     12        Tonya Holland       South Zone             2.697112e+08
38     22      Michele Stewart       South Zone             2.670736e+08
39     38         Brooke Allen       South Zone             2.564386e+08
40     25       Nicole Navarro       South Zone             2.544957e+08
41     18          Briana Hart       South Zone             2.528669e+08
42     10      Victoria Nelson       South Zone             2.499800e+08
43     29     Richard Lawrence       South Zone             2.472093e+08
44     28       Laurie Ramirez        West Zone             2.628508e+08
45     32      Samantha Garcia        West Zone             2.575997e+08
46     47      Teresa Townsend        West Zone             2.559805e+08
47      6      Jennifer Pruitt        West Zone             2.543830e+08
48     36       Edward Alvarez        West Zone             2.483344e+08
49     44         Theresa Long        West Zone             2.411666e+08

    rank_within_territory
0                       1
1                       2
2                       3
3                       4
4                       5
5                       6
6                       7
7                       8
8                       1
9                       2
10                      3
11                      4
12                      5
13                      6
14                      7
15                      8
16                      9
17                     10
18                     11
19                     12
20                     13
21                      1
22                      2
23                      3
24                      4
25                      5
26                      6
27                      7
28                      8
29                      9
30                     10
31                     11
32                      1
33                      2
34                      3
35                      4
36                      1
37                      2
38                      3
39                      4
40                      5
41                      6
42                      7
43                      8
44                      1
45                      2
46                      3
47                      4
48                      5
49                      6

In [11]:
doctor_trend_query = """
WITH monthly_doctor_revenue AS (
    -- STEP A: Collapse transactions into one row per doctor, per month
    SELECT 
        d.doctor_id,
        d.doctor_name,
        d.specialization,
        strftime('%Y-%m', s.transaction_date) AS sales_month,
        SUM(s.total_revenue) AS monthly_revenue
    FROM sales AS s
    JOIN doctors AS d ON s.doctor_id = d.doctor_id
    GROUP BY d.doctor_id, d.doctor_name, d.specialization, sales_month
)

-- STEP B: Now compare each doctor's month to their OWN previous month
SELECT 
    doctor_id,
    doctor_name,
    specialization,
    sales_month,
    monthly_revenue,
    LAG(monthly_revenue) OVER (
        PARTITION BY doctor_id 
        ORDER BY sales_month
    ) AS previous_month_revenue,
    ROUND(
        (monthly_revenue - LAG(monthly_revenue) OVER (PARTITION BY doctor_id ORDER BY sales_month)) 
        * 100.0 / LAG(monthly_revenue) OVER (PARTITION BY doctor_id ORDER BY sales_month), 
        2
    ) AS pct_change_vs_last_month
FROM monthly_doctor_revenue
ORDER BY doctor_id, sales_month
"""

doctor_trend_df = pd.read_sql(doctor_trend_query, conn)
print(doctor_trend_df.head(20))
at_risk_doctors = doctor_trend_df[doctor_trend_df["pct_change_vs_last_month"] < -50]
print("\nNumber of doctor-months flagged as 'at risk' (revenue dropped >50%):", len(at_risk_doctors))
print(at_risk_doctors.head(10))

    doctor_id         doctor_name specialization sales_month  monthly_revenue  \
0           1  Dr. Valerie Jensen   Cardiologist     2024-09        689571.35
1           1  Dr. Valerie Jensen   Cardiologist     2024-10       2264357.47
2           1  Dr. Valerie Jensen   Cardiologist     2024-11       1252027.50
3           1  Dr. Valerie Jensen   Cardiologist     2024-12       4063007.28
4           1  Dr. Valerie Jensen   Cardiologist     2025-01       6040810.38
5           1  Dr. Valerie Jensen   Cardiologist     2025-02       1741974.55
6           1  Dr. Valerie Jensen   Cardiologist     2025-03       1273971.42
7           1  Dr. Valerie Jensen   Cardiologist     2025-04       1486766.01
8           1  Dr. Valerie Jensen   Cardiologist     2025-05       3676047.81
9           1  Dr. Valerie Jensen   Cardiologist     2025-06       2799451.91
10          1  Dr. Valerie Jensen   Cardiologist     2025-07       3390010.54
11          1  Dr. Valerie Jensen   Cardiologist     2025-08       3844749.61
12          1  Dr. Valerie Jensen   Cardiologist     2025-09       2318004.30
13          1  Dr. Valerie Jensen   Cardiologist     2025-10       1336369.15
14          1  Dr. Valerie Jensen   Cardiologist     2025-11       3113518.10
15          1  Dr. Valerie Jensen   Cardiologist     2025-12       3588230.89
16          1  Dr. Valerie Jensen   Cardiologist     2026-01       3834257.86
17          1  Dr. Valerie Jensen   Cardiologist     2026-02       2676594.14
18          1  Dr. Valerie Jensen   Cardiologist     2026-03       2385221.15
19          1  Dr. Valerie Jensen   Cardiologist     2026-04       4435526.58

    previous_month_revenue  pct_change_vs_last_month
0                      NaN                       NaN
1                689571.35                    228.37
2               2264357.47                    -44.71
3               1252027.50                    224.51
4               4063007.28                     48.68
5               6040810.38                    -71.16
6               1741974.55                    -26.87
7               1273971.42                     16.70
8               1486766.01                    147.25
9               3676047.81                    -23.85
10              2799451.91                     21.10
11              3390010.54                     13.41
12              3844749.61                    -39.71
13              2318004.30                    -42.35
14              1336369.15                    132.98
15              3113518.10                     15.25
16              3588230.89                      6.86
17              3834257.86                    -30.19
18              2676594.14                    -10.89
19              2385221.15                     85.96

Number of doctor-months flagged as 'at risk' (revenue dropped >50%): 674
    doctor_id         doctor_name specialization sales_month  monthly_revenue  \
5           1  Dr. Valerie Jensen   Cardiologist     2025-02       1741974.55
20          1  Dr. Valerie Jensen   Cardiologist     2026-05       1831828.84
22          1  Dr. Valerie Jensen   Cardiologist     2026-07       1547834.38
28          2     Dr. Ashley Holt   Cardiologist     2024-12       1497545.85
31          2     Dr. Ashley Holt   Cardiologist     2025-03       1616232.22
36          2     Dr. Ashley Holt   Cardiologist     2025-08       1493814.91
39          2     Dr. Ashley Holt   Cardiologist     2025-11        486003.44
45          2     Dr. Ashley Holt   Cardiologist     2026-05       1307953.55
49          2     Dr. Ashley Holt   Cardiologist     2026-09        547084.40
61          3  Dr. Emily Crawford  Dermatologist     2025-08        525863.96

    previous_month_revenue  pct_change_vs_last_month
5               6040810.38                    -71.16
20              4435526.58                    -58.70
22              3128058.65                    -50.52
28              4164997.61                    -64.04
31              3757857.19                    -56.99
36              4366258.47                    -65.79
39              2165677.86                    -77.56
45              3570543.31                    -63.37
49              4945499.20                    -88.94
61              5023352.39                    -89.53

In [12]:
mr_revenue_query = """
SELECT 
    m.mr_id,
    m.mr_name,
    m.territory,
    COUNT(*) AS total_transactions,
    SUM(s.total_revenue) AS total_revenue_generated,
    ROUND(AVG(s.total_revenue), 2) AS avg_revenue_per_sale
FROM sales AS s
JOIN medical_representatives AS m ON s.mr_id = m.mr_id
GROUP BY m.mr_id, m.mr_name, m.territory
ORDER BY total_revenue_generated DESC
"""
mr_revenue_df = pd.read_sql(mr_revenue_query, conn)
mr_revenue_df.to_csv("mr_incentive_summary.csv", index=False)
messy_sales_df.to_csv("full_sales_transactions.csv", index=False)
doctors_df.to_csv("doctors_registry.csv", index=False)
print("Exported 3 files successfully:")
print("1. mr_incentive_summary.csv")
print("2. full_sales_transactions.csv")
print("3. doctors_registry.csv")
conn.close()

Exported 3 files successfully:
1. mr_incentive_summary.csv
2. full_sales_transactions.csv
3. doctors_registry.csv

In [13]:
import os
print("Current working directory:", os.getcwd())
print("\nFiles in this folder:")
print(os.listdir())
conn_check = sqlite3.connect("pharma_sales.db")
tables = pd.read_sql("SELECT name FROM sqlite_master WHERE type='table';", conn_check)
print("\nTables found inside pharma_sales.db:")
print(tables)
conn_check.close()

Current working directory: c:\Users\sanje\Desktop\Project 1

Files in this folder:
['01_pharma_sales_master_pipeline.ipynb', 'doctors_registry.csv', 'full_sales_transactions.csv', 'mr_incentive_summary.csv', 'pharma_sales.db']

Tables found inside pharma_sales.db:
                      name
0                    sales
1  medical_representatives
2                  doctors

In [14]:
conn = sqlite3.connect("pharma_sales.db")
doctor_segmentation_query = """
SELECT 
    d.doctor_id,
    d.doctor_name,
    d.specialization,
    COUNT(*) AS total_orders,
    SUM(s.total_revenue) AS total_revenue_generated
FROM sales AS s
JOIN doctors AS d ON s.doctor_id = d.doctor_id
GROUP BY d.doctor_id, d.doctor_name, d.specialization
ORDER BY total_revenue_generated DESC
"""

doctor_segmentation_df = pd.read_sql(doctor_segmentation_query, conn)
doctor_segmentation_df.to_csv("doctor_segmentation.csv", index=False)

print("Exported doctor_segmentation.csv with", len(doctor_segmentation_df), "doctors")

conn.close()

Exported doctor_segmentation.csv with 200 doctors